### ISSUE TITLE
Reuse workers we create and never create more than `navigator.hardwareConcurrency - 1` workers

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/exu#3]
According to the html standard https://html.spec.whatwg.org/multipage/workers.html#scope-2

> Generally, workers are expected to be long-lived, have a high start-up performance cost, and a high per-instance memory cost.

Then we should maintain a thread pool of workers and reuse them everytime, do not create more workers than that. 

A user can crash someone's browser if `wasm.task()` is put in a infinite busy loop.

Another reason this needs to be solved is that the spec mentions Workers are heavy objects, creating and terminating them is an expensive operation and the library currently terminates worker after each call when it should never call terminate ever

**Comment by Daksh14** [comment]
This is needed for https://github.com/dusk-network/dusk-wallet-js/issues/78 as to inform about progression, we would have to call the web assembly function in a loop which would cause overloading of worker creations and slowdown of the application drastically. 

For the while the dusk-wallet-js has implemented the fix of putting the awaits in an array of length `navigator.hardwareConcurrency - 1` and Promise.all and wait for those tasks to finish before putting other ones

**Comment by ZER0** [comment]
As discussed multiple times, the purpose of `exu` is *not* to parallelize code, but to execute web assembly function in a sandboxed, isolated, abortable "thread".

For such reason, having a pool of workers wouldn't make sense, since it means the library is misused (e.g. we shouldn't hit the `navigator.hardwareConcurrency`, and even if it's the case we don't care if the code is actually running in parallel).

I will close this as "wontifx", and creating the issue that reporting the *actual* problem and not just directly *one of the possible solutions*.
